---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-edit-rb
  namespace: <your-namespace>
subjects:
  - kind: ServiceAccount
    name: pipelines-sa
    namespace: <your-namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
