apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-sa
imagePullSecrets:
  - name: registry-credentials
secrets:
  - name: semantic-release-auth
  - name: registry-credentials
  - name: github-webhook-config
