apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: semantic-release-image-repo

spec:
  url: "https://github.com/StinkyBenji/semantic-release-image"
  git_provider:
    secret:
      name: "github-webhook-config"
      key: "provider.token"
    webhook_secret:
      name: "github-webhook-config"
      key: "webhook.secret"
