kind: ConfigMap
apiVersion: v1
metadata:
  name: chains-config
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
    operator.tekton.dev/operand-name: tektoncd-chains
data:
  artifacts.oci.repository: "quay.io"
  artifacts.oci.storage: "oci"
  artifacts.pipelinerun.format: in-toto
  artifacts.pipelinerun.storage: "tekton"
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.storage: "tekton"
  transparency.enabled: "true"
  transparency.url: https://rekor.apps.ocp4.whatever.out-of-my-head.de
  signers.x509.fulcio.enabled: "true"
  signers.x509.fulcio.address: https://fulcio.apps.ocp4.whatever.out-of-my-head.de
