kind: ConfigMap
apiVersion: v1
metadata:
  name: chains-config
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
    operator.tekton.dev/operand-name: tektoncd-chains
data:
  artifacts.oci.storage: "oci"
  artifacts.pipelinerun.storage: oci
  artifacts.taskrun.storage: "oci"
  transparency.enabled: "true"
  transparency.url: https://rekor.apps.ocp4.whatever.out-of-my-head.de
  signers.x509.fulcio.enabled: "true"
  signers.x509.fulcio.address: https://fulcio.apps.ocp4.whatever.out-of-my-head.de
  signers.x509.fulcio.issuer: https://keycloak-keycloak-system.apps.ocp4.whatever.out-of-my-head.de/auth/realms/sigstore
  signers.x509.tuf.mirror.url: https://tuf.apps.ocp4.whatever.out-of-my-head.de
