kind: ConfigMap
apiVersion: v1
metadata:
  name: chains-config
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
    operator.tekton.dev/operand-name: tektoncd-chains
data:
  artifacts.oci.repository: "quay.io"
  artifacts.oci.storage: "tekton,oci"
  artifacts.pipelinerun.format: slsa/v1
  artifacts.pipelinerun.storage: "tekton,oci"
  artifacts.taskrun.format: slsa/v1
  artifacts.taskrun.storage: "tekton,oci"
  transparency.enabled: "true"
